// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyBepAn.Data;

#nullable disable

namespace QuanLyBepAn.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyBepAn.Models.Kho", b =>
                {
                    b.Property<int>("MaKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKho"));

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("int");

                    b.Property<double>("SoLuongTon")
                        .HasColumnType("float");

                    b.HasKey("MaKho");

                    b.HasIndex("MaNguyenLieu");

                    b.ToTable("Kho");
                });

            modelBuilder.Entity("QuanLyBepAn.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaQuyen");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("QuanLyBepAn.Models.NguyenLieu", b =>
                {
                    b.Property<int>("MaNguyenLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguyenLieu"));

                    b.Property<double?>("Cali")
                        .HasColumnType("float");

                    b.Property<double?>("Calo")
                        .HasColumnType("float");

                    b.Property<double?>("Dam")
                        .HasColumnType("float");

                    b.Property<double>("GiaTriDinhDuong")
                        .HasColumnType("float");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguyenLieu");

                    b.ToTable("NguyenLieu");
                });

            modelBuilder.Entity("QuanLyBepAn.Models.NhatKyHeThong", b =>
                {
                    b.Property<int>("MaLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLog"));

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLog");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("NhatKyHeThong");
                });

            modelBuilder.Entity("QuanLyBepAn.Models.Quyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaQuyen");

                    b.ToTable("Quyen");
                });

            modelBuilder.Entity("QuanLyBepAn.Models.ThucDon", b =>
                {
                    b.Property<int>("MaThucDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThucDon"));

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("datetime2");

                    b.Property<double>("TongCalo")
                        .HasColumnType("float");

                    b.HasKey("MaThucDon");

                    b.ToTable("ThucDon");
                });

            modelBuilder.Entity("QuanLyBepAn.Models.ThucDonItem", b =>
                {
                    b.Property<int>("MaThucDonItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThucDonItem"));

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("int");

                    b.Property<int>("MaThucDon")
                        .HasColumnType("int");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.HasKey("MaThucDonItem");

                    b.HasIndex("MaNguyenLieu");

                    b.HasIndex("MaThucDon");

                    b.ToTable("ThucDonItem");
                });

            modelBuilder.Entity("QuanLyBepAn.Models.Kho", b =>
                {
                    b.HasOne("QuanLyBepAn.Models.NguyenLieu", "NguyenLieu")
                        .WithMany()
                        .HasForeignKey("MaNguyenLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("QuanLyBepAn.Models.NguoiDung", b =>
                {
                    b.HasOne("QuanLyBepAn.Models.Quyen", "Quyen")
                        .WithMany()
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("QuanLyBepAn.Models.NhatKyHeThong", b =>
                {
                    b.HasOne("QuanLyBepAn.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyBepAn.Models.ThucDonItem", b =>
                {
                    b.HasOne("QuanLyBepAn.Models.NguyenLieu", "NguyenLieu")
                        .WithMany()
                        .HasForeignKey("MaNguyenLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBepAn.Models.ThucDon", "ThucDon")
                        .WithMany()
                        .HasForeignKey("MaThucDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");

                    b.Navigation("ThucDon");
                });
#pragma warning restore 612, 618
        }
    }
}
